#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

if (file_exists($autoload = __DIR__.'/vendor/autoload.php')) {
    require $autoload;
}

$app = require_once __DIR__.'/bootstrap/app.php';

$status = $app->handleCommand(new Symfony\Component\Console\Input\ArgvInput);

exit($status);